name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "lodekennes/mycloudbuilder"
          platforms: linux/amd64,linux/arm64
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.cpu
          context: .
          tags: |
            ghcr.io/intellua/vllm/vllm-cpu:latest
            ghcr.io/intellua/vllm/vllm-cpu:${{github.run_number}}
          platforms: linux/amd64
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
