name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -f Dockerfile.cpu -t ghcr.io/intellua/vllm/vllm-cpu:latest -t ghcr.io/intellua/vllm/vllm-cpu:${{github.run_number}} --push --shm-size=4g . 
